### ISSUE TITLE
Exclude not excluding

### ISSUE THREAD

**Issue by negebauer** [jpsim/SourceKitten#217]
I'm using the pod [R.swift](https://github.com/mac-cain13/R.swift) which generates a folder named `R.swift` on the Pods folder

jazzy is trying to read the contents of `R.swift` and fails (logical, it's a folder, not a file)

I'm calling it using `jazzy --exclude R.swift,Pods/*` but it keeps crashing

How can I correctly ignore the R.swift folder?

**Comment by jpsim** [comment]
This was a jazzy issue, unrelated to this project, and it was fixed in realm/jazzy#542

**Comment by negebauer** [comment]
This is still failling for me as of `v.0.6.3`
I get this log
```
Could not read contents of `-I/Users/Nico/Documents/Xcode/Wifi UC/Pods/Headers/Public/R.swift`
Could not parse `R.swift`. Please open an issue at https://github.com/jpsim/SourceKitten/issues with the file contents.
building site
jam out ♪♫ to your fresh new docs in `docs`
```

Should I open an issue in `jazzy`?

**Comment by jpsim** [comment]
Yes please

**Comment by negebauer** [comment]
Done! opened realm/jazzy#586
